### ISSUE TITLE
SIGALRM crash with ::API controllers

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#101]
We've had 4 reports of the BETA ScoutProf agent crashing with a `SIGALRM` error under the following conditions:

* The app has controllers that inherit from `ActionController::API` vs. `ActionController::Base` and our instrumentation is manually included via [our help docs](http://help.apm.scoutapp.com/#actioncontroller-metal).
* ScoutProf is enabled
* In at least two cases, the app is running inside a Docker container (either tests, Circle CI)
* It's been observed w/Rails 4 and 5 and Ruby 2.3 and Ruby 2.2

@cschneid has tried to reproduce locally with a Rails 5 app w/o success.

**Comment by dlanderson** [comment]
Rails 5.1.1
Puma Version 3.9.1 - min threads: 5, max threads: 5
Ruby 2.3.1-p112

Controller Inheriting from both `ActionController::API` and `ActionController::Metal`

In a docker container from Ubuntu 16.04, with `bundle exec rails s` as entry point and manually hitting endpoint in browser, and with entry point as running tests, was unable to replicate.

I'll try a CircleCI build next

**Comment by dlanderson** [comment]
I was able to reproduce similar behavior by preventing the agent background worker to start. 3.0.0.pre10 adds a check to make sure ScoutProf has set up the signal handlers, regardless of how our instrumentation was included.

**Comment by dlanderson** [comment]
Version 3.0.0.pre10 fixes this issue for the reports we've received.
