### ISSUE TITLE
DevTrace should be easy to inject manually

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#106]
Many people who use Single Page Apps (react / angular / ember) serve static html as their initial load, and don't go through the Rails middleware.

Since it doesn't go through middleware, the DevTrace javascript doesn't get injected.

We should make sure the DevTrace javascript can be included directly via a script tag into a user's non-rails HTML, and start reading XHR requests made to an instrumented Rails application.

**Comment by jairodemorais** [comment]
+1 here

**Comment by jonekdahl** [comment]
I think this is a great idea. #132 is similar and has some more details.

**Comment by adamtsis** [comment]
+1

**Comment by ckornaros** [comment]
We use Rails with React and it will really great that ajax request works. Can we do anything to help with this feature ?

**Comment by joegaudet** [comment]
:+1 to this.

**Comment by sgomez17** [comment]
+1

**Comment by blindMoe** [comment]
+1

**Comment by krue-doug** [comment]
Any updates on this?

**Comment by bf4** [comment]
I imagine in a SPA or api-only app it would be something like https://github.com/MiniProfiler/rack-mini-profiler/issues/139#issuecomment-310481298 where I made an initializer as pasted below

I'm not sure which part of the scout app should be used for this, and imagine it depends on the storage type for the 'speed badge'.


```ruby
# config/initializers/mini_profiler.rb

  Rails.application.routes.append do
    mini_profiler = Rack::MiniProfiler.new(Rails.application)
    get '/profiler' => ->(env) {
      [200, {}, [<<-BODY.strip_heredoc]]
      <html>
      <head>
      </head>
      <body>
      #{mini_profiler.get_profile_script(env)}
      </body>
      </html>
      BODY
    }
  end
```

**Comment by itsderek23** [comment]
We've been thinking about the best way to future-proof DevTrace so a trace is always available and doesn't add to the complexity of rendering DevTrace. 

One thought: we return a request header with a link to the URL of the trace. You can then access this with browser development tools and/or a browser extension.

This would also make it possible for us to provide instant traces in production (see similar-ish logic in our [server timing gem](https://github.com/scoutapp/ruby_server_timing)).

**Comment by YoranBrondsema** [comment]
@itsderek23 I think that would be a good start. Right now we're forced to keep using an version 4 of New Relic for its Developer Mode. As far as I know, that's the only way for us to debug slow transactions with n+1 queries locally (we have an SPA).

Any ETA on this feature?

**Comment by joegaudet** [comment]
@itsderek23 that would be fantastic.

**Comment by joegaudet** [comment]
@itsderek23 just bumping this, would love something like this for local development.

**Comment by ioquatix** [comment]
@itsderek23 @cschneid would you like me to investigate where we are with this?

**Comment by joegaudet** [comment]
@itsderek23 any movement on this?

**Comment by joegaudet** [comment]
@dlanderson just saw that this is closed, does that mean it's been handled or ignored?

**Comment by Nittarab** [comment]
no update?
