### ISSUE TITLE
Allow DevTrace to run on non-development environments

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#121]
A few people have wanted to run DevTrace against their staging environment, or other remote environment.

Right now, we [never even insert](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm.rb#L177) the DevTrace middleware if the rails environment isn't exactly `development`.

Ideally this would move to an environment variable - perhaps another flag, or set of flags to override our dev-only check, and/or add some security checks.  Would have to balance the need for security and usability. Don't want to make it too easy to allow customers to accidentally expose devtrace to their customers.

**Comment by dlanderson** [comment]
Same issue, but in Roadmap: https://github.com/scoutapp/roadmap/issues/7
