### ISSUE TITLE
Que Support

### ISSUE THREAD

**Issue by langsharpe** [scoutapp/scout_apm_ruby#126]
Add support for Que (https://github.com/chanks/que) background jobs.

**Comment by nearapogee** [comment]
Any word on this? I would be interested in helping. Is there a reason it hasn't been added yet?

**Comment by ioquatix** [comment]
We are implementing this here: https://github.com/scoutapp/scout_apm_ruby/pull/265

**Comment by dlanderson** [comment]
Support for Que was [released in 2.5.6](https://github.com/scoutapp/scout_apm_ruby/blob/master/CHANGELOG.markdown#253)
