### ISSUE TITLE
Fix DevTrace incompatibilities with other gems

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#133]
There are a handful of reports that other gems may interfere with DevTrace (or the other way around).

* Bullet

**Comment by Nittarab** [comment]
Any update about this?  It would be very usefull

**Comment by Nittarab** [comment]
@itsderek23 - Yes, if Bullet is enable and notify mi about N+1 query i don't see the scout_instant_bage.

Bullet config: 
```
config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = false
    Bullet.console = true
    Bullet.add_footer = false
    Bullet.stacktrace_includes = [ 'your_gem', 'your_middleware' ]
    Bullet.stacktrace_excludes = [ 'their_gem', 'their_middleware', ['my_file.rb', 'my_method'], ['my_file.rb', 16..20] ]
  end
```

**Comment by narze** [comment]
I second that Scout badge will not appear when Bullet is enabled.

My workaround is disabling the bullet when setting SCOUT_DEV_TRACE

```
    if ENV['SCOUT_DEV_TRACE'] == 'true'
      Bullet.enable = false
    else
      Bullet.enable = true
    end
```

It would be nice if both can be run together though.
