### ISSUE TITLE
Instrument Puma correctly when launched via `rails server`

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#135]
Right now, we often won't setup instrumentation correctly when launching Rails via `rails server`, when it in turn delegates to launching puma.

An easy workaround exists: `bundle exec puma` directly.

**Comment by itsderek23** [comment]
@cschneid - this has been addressed, correct?

**Comment by cschneid** [comment]
Yes, I added a few additional spots to ensure that the background worker is launched when needed.

Those changes are in 2.3.2+
