### ISSUE TITLE
Capture SQL statements on `update` and `insert` statements

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#139]
It appears that we do no collect SQL query statements on `update` and `insert` SQL statements, triggered by ActiveRecord `save/create` like we do for SQL `select`. 

I haven't checked for `delete` statements.

**Comment by cschneid** [comment]
This was added in 2.3.3. We should now be capturing Inserts, Deletes, and Updates.

![database_monitoring](https://user-images.githubusercontent.com/6119/35362909-9ba319d4-0124-11e8-93a5-e1578ae6e32f.png)
