### ISSUE TITLE
Issues detecting Puma via Heroku / Procfile

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#151]
We've had reports that `scout_apm` does not automatically start if nothing is defined for `web` in a `Procfile`.

Heroku defaults to `bundle exec rails server`. Adding `web: bundle exec puma` fixes the issue.

**Comment by aaronjensen** [comment]
On 3.0.0.pre18, it doesn't seem to start ever for us on Heroku or in a docker container (both run bundle exec rails server).

On 3.0.0.pre15, it starts, but the log indicates that it is starting Webrick. Will this cause problems with our metrics?

**Comment by dlanderson** [comment]
@aaronjensen No, the `webrick` detection in `3.0.0.pre15` should not affect your metrics. If you set your procfile to `bundle exec puma ...` it should work in `3.0.0.pre18`. We are continuing to look into making the agent work reliably with `bundle exec rails server` when using puma.

**Comment by cschneid** [comment]
We just released 2.4.5 and 3.0.0.pre19 with a fix for missing metrics.

In some cases (primarily puma, when launched indirectly via `rails server`) we didn't install the instruments. So the agent was up and running, but all of the library instrumentation wasn't there, so nothing was recorded.

@aaronjensen - Can you give it a try?

**Comment by aaronjensen** [comment]
Seems to be working for us, thanks!

**Comment by cschneid** [comment]
Thank you for verifying, closing this issue - let us know if you have any other questions.
