### ISSUE TITLE
Resque jobs are not recorded

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_ruby#152]
In v2.4.0-v2.4.3, the recorder for Resque jobs is not correctly set to the remote recorder. This prevents Resque jobs from being recorded/reported to APM. This should be fixed in https://github.com/scoutapp/scout_apm_ruby/commit/30c14773c84a1d512a90f7f4d064411a86285a36 and will be released in 2.4.4.

**Comment by cschneid** [comment]
Fixed and Released in 2.4.4
