### ISSUE TITLE
Net::HTTP layers can be double counted

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_ruby#153]
When using Faraday using the default adapter (Net::HTTP), if rest-client is also installed it can cause double-counting of the number of HTTP requests. This commit ignores any children of Net::HTTP.request calls. Affects version <= 2.4.3.

Fixed in PR https://github.com/scoutapp/scout_apm_ruby/pull/146

Will be released in 2.4.4

**Comment by cschneid** [comment]
Released in 2.4.4
