### ISSUE TITLE
Agent is starting sometimes, even with monitor=false

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#154]
In 2.4.0-2.4.3, the agent was starting in some situations where it shouldn't have.

This is fixed on master in f7a8b3fb35

**Comment by itsderek23** [comment]
This can show more deploys for an app than expected in the UI as it picks up local Git SHAs.

**Comment by cschneid** [comment]
Fixed & Released in 2.4.4
