### ISSUE TITLE
`Mysql2::Error - Can’t connect to MySQL server` error w/ScoutProf enabled

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#173]
We've had 2 reports of the following error when ScoutProf is enabled. Switching back to the non-BETA gem resolves the issue:

`Mysql2::Error - Can’t connect to MySQL server on ...`

**Comment by dlanderson** [comment]
ScoutProf has been removed and replaced by [AutoInstruments](https://scoutapm.com/docs/ruby/advanced-features#auto-instruments)
