### ISSUE TITLE
Instrument Memcached

### ISSUE THREAD

**Issue by hooopo** [scoutapp/scout_apm_ruby#174]
![image](https://user-images.githubusercontent.com/63877/38038819-73dc776a-32de-11e8-93a6-464b8dd77b4d.png)
I use memcached with dalli as cache store, but can not see instrument in scout web ui, will scout support memecachd?

**Comment by chaner** [comment]
I would also love this out of the box

**Comment by dlanderson** [comment]
Closing - support was added a while ago in #279
