### ISSUE TITLE
DevTrace fails to display traces from React requests triggered via the fetch API

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#175]
Probably missing a listener...

[Fetch API Docs](https://facebook.github.io/react-native/docs/network.html)

**Comment by shyam-habarakada** [comment]
Yes, missing a listener. Although I am not sure if the `fetch` API allows global hooks like that without a custom wrapper. What might be better is to expose a method that developers can hook so they can call it to prompt scout to go collect metrics. Just a thought... there are other open source tools that follow this pattern as a workaround
