### ISSUE TITLE
Add Typhoeus instrumentation

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#177]

**Comment by mjsommer** [comment]
Thanks! As mentioned, I am replacing some of my RestClient and Net::HTTP calls, and don't see the Typhoeus replacement coming through.

**Comment by mjobin-mdsol** [comment]
We are also looking for this

**Comment by mjobin-mdsol** [comment]
Draft -- would that work?

https://github.com/mjobin-mdsol/scout_apm_ruby/commit/2abfcb121836f2fa2202ba5765cf474f6624878b

**Comment by mjobin-mdsol** [comment]
https://github.com/scoutapp/scout_apm_ruby/pull/371

**Comment by mjobin-mdsol** [comment]
v4.0.3 🎉

**Comment by dlanderson** [comment]
Closing - As indicated, Typhoeus was added in 4.0.3.
