### ISSUE TITLE
Custom context

### ISSUE THREAD

**Issue by mapreal19** [scoutapp/scout_apm_ruby#181]
I'm trying to add some custom context per the docs: http://help.apm.scoutapp.com/#ruby-custom-context

But I'm not seeing any custom context on the traces. Anything I'm doing wrong?

Code on a before_action:

```ruby
context = {
  user_email: current_user&.email,
  user_id: current_user&.id
}
ScoutApm::Context.add(context)
```

* Using Rails 5.1 and Scout configured using ENV variables: SCOUT_KEY, SCOUT_MONITOR, SECRET_KEY_BASE

**Comment by cschneid** [comment]
Would you mind emailing us at support@scoutapp.com with a link to a trace that should have this data?

**Comment by mapreal19** [comment]
@cschneid sure, thanks!
