### ISSUE TITLE
ActiveRecordSlave gem prevents capturing SQL

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#190]
This appears to be some bad interaction between the two gems on the Database tab, and is allocating every query to `Slave#other` and not capturing any queries during that time.

It doesn't appear to be breaking individual queries inside traces, but I haven't investigated deep enough to be sure.

https://github.com/rocketjob/active_record_slave

![image](https://user-images.githubusercontent.com/6119/39587088-e6b86ac6-4eb5-11e8-95d4-627819403d70.png)

**Comment by Cervenka** [comment]
Is there maybe an update to this?
Thank you!

**Comment by Cervenka** [comment]
I did make a change to the active_record_gem to make this work again. Thanks
