### ISSUE TITLE
Shoryuken instrumentation

### ISSUE THREAD

**Issue by steveh** [scoutapp/scout_apm_ruby#195]
I would appreciate instrumentation for the Amazon SQS background job worker, [Shoryuken](https://github.com/phstc/shoryuken).

It has [middleware](https://github.com/phstc/shoryuken/wiki/Middleware) based on Sidekiq.

**Comment by tzar** [comment]
Also looking for this

**Comment by vbalazs** [comment]
@steveh do you mind reopening this please? several of us was tracking this issue and we would still appreciate this, even if you don't need it anymore :) maybe you can unsubscribe?

Or if that is not possible I can clone this one under my name.

**Comment by cschneid** [comment]
This is still on my radar, to get done soon. I'll reopen - @steveh you can use the github unsubscribe button on the right side to prevent any future notifications.
