### ISSUE TITLE
Track time-in-queue for AWS ALB via the `X-Amzn-Trace-Id` header

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#196]
I believe we're unable to track time-in-queue for apps that directly receive traffic from AWS ALBs as these requests lack a [supported x-request-start-like header](https://github.com/scoutapp/scout_apm_ruby/blob/c805e10520231390eaaadb8aad6258ba0aad6ca9/lib/scout_apm/layer_converters/request_queue_time_converter.rb#L5). 

However, it looks like we can parse this information from the [X-Amzn-Trace-Id header](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html).

Example:

```
X-Amzn-Trace-Id: Self=1-67891234-12456789abcdef012345678;Root=1-67891233-abcdef012345678912345678;CalledFrom=app
```
`67891234` is the epoch time, in seconds.

Our parsing logic would need to be updated as this is a significantly different format.

**Comment by nateberkopec** [comment]
Actually would this even be useful? Time since epoch in seconds isn't high-resolution enough.

**Comment by ioquatix** [comment]
You are right, it doesn't seem to be very precise, is that actually the state of it today?

**Comment by emilyst** [comment]
Seems like a request for `X-Request-Start` has been hanging out for nine years: https://forums.aws.amazon.com/message.jspa?messageID=396283

**Comment by scalp42** [comment]
We're running behind AWS ALBs and anything would help us.

**Comment by nateberkopec** [comment]
The only thing I've seen work is for you to run your own reverse proxy on each individual instance. e.g nginx, passenger standalone, apache, etc.

**Comment by dlanderson** [comment]
Measuring in seconds is too granular and it doesn't look like AWS will be adding ms any time soon. Closing
