### ISSUE TITLE
Control characters in SQL cause issues in ingestion

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#199]
After investigation of #197, I narrowed things down to the `niceql` gem. It overrides ActiveRecord's `log` method (which is the AR method that wraps the actual sql request to the database, it does more than the name implies). 

The overrided `log`  from `niceql` converts the sql into a colorized / pretty form of the same SQL (with console style ascii control characters).

`scout_apm_ruby` captures that sql, and sends it up alongside the rest of the metrics.

The issue is that the sql captured in this case contains non printable characters `"\u001b[?;?;49mSELECT\u001b[0m  ... `. This causes our ingestion pipeline to reject the sql when parsing it. (specifically, `\u001b` is the escape control character, and not valid in a JSON string).

The SQL capture in the agent should be changed to strip non-printable characters in order to account for this.

**Comment by dlanderson** [comment]
Haven't hit this issue in years, closing.
