### ISSUE TITLE
How to install instruments in custom class?

### ISSUE THREAD

**Issue by aharpervc** [scoutapp/scout_apm_ruby#203]
Circa `3.0.0.pre10`, I had a custom instrumentation setup, which is now (`3.0.0.pre25`) not working. I want to know how to get my setup working again.

What I had that was working looked like this:

```ruby
module ScoutApmInstrumentation
  module Instruments
    class MyClass

      def initalize(logger = ScoutApm::Agent.instance.logger)
        @logger = logger
        @installed = false
      end

      def installed?
        @installed
      end

      def install
        @installed = true

        if defined?(::MyOtherClass)
          ScoutApm::Agent.instance.logger.info 'Instrumenting MyOtherClass'

          ::MyOtherClass.class_eval do
            include ScoutApm::Tracer

            instrument_method :a, type: 'Thing1'
            instrument_method :b, type: 'Thing2'
          end
        end

        # more, but you get the idea

      end
    end
  end
end
```

Then to get it installed, right after the class definition there I called:

```ruby
ScoutApm::Agent.instance.install_instrument ScoutApmInstrumentation::Instruments::MyClass
```

And it all worked great.

However, as I said currently this does not work any more. It looks like `install_instrument` has been moved to `InstrumentManager` but other than observing that I didn't see how to hook this up.

**Comment by dlanderson** [comment]
Hi @aharpervc - we usually recommend doing the instrumentation within your class definition as [shown in the help docs](http://help.apm.scoutapp.com/#ruby-custom-instrumentation).

If you want to keep the Scout instrumentation outside of the class files themselves you can also do that. Instead of using `InstrumentManager.install_instrument`, check for `installed?` within the install method (`if !installed? && defined?(::MyOtherClass)`), and call `ScoutApmInstrumentation::Instruments::MyClass.new.install`.

**Comment by aharpervc** [comment]
> Hi @aharpervc - we usually recommend doing the instrumentation within your class definition as shown in the help docs.

I don't care to research it, but I'm fairly certain there was an example along the lines of what I originally wrote either in docs or as a code example in this repo. I get that v3 is still a prerelease though, so I'm along for the ride on that. Also, in this situation, `MyOtherClass` may not take a direct dependency on scout, hence needing to hook up the instrumentation from the outside regardless.

Your solution makes sense. However, I'm wondering if I need this custom instrumentation class at all. This code lives in a rails initializer, so if it just exists to get new'd up & have the install method called, why not just run the instrument logic directly without the ceremony? Eg:

```ruby
# delete all of the previous example, replace with:

if defined?(::MyOtherClass)
  ScoutApm::Agent.instance.logger.info 'Instrumenting MyOtherClass'

  ::MyOtherClass.class_eval do
    include ScoutApm::Tracer

    instrument_method :a, type: 'Thing1'
    instrument_method :b, type: 'Thing2'
  end
end
```

And also, I believe I can guarantee that `MyOtherClass` will exist by this point, so probably don't even need that.

Thoughts?

**Comment by dlanderson** [comment]
Yes, that's completely fine to do as well. The only requirements are `include ScoutApm::Tracer` and the `instrument_method :a, type: 'Thing1'` either within the class itself or via class_eval. Outside of that, it doesn't matter how it's called.

Just in case the link to the docs didn't come through on my previous comment: http://help.apm.scoutapp.com/#instrumenting-method-calls

Going to go ahead and close this issue. Feel free to contact us at support@scoutapp.com or hop into our Slack channels at http://slack.scoutapp.com/

**Comment by aharpervc** [comment]
Great, thanks for the help
