### ISSUE TITLE
Incorrect SQL Query Naming with a Relation object

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#207]
A customer is seeing SQL named as `#<User::ActiveRecord_Relation:0x007fa6fc0da200>#other` instead of the correct `User#other` name.

I think we're calling `.to_s` somewhere, where we actually need to be calling `.name`

```
[16] pry(main)> User.where(name: "").to_s
=> "#<User::ActiveRecord_Relation:0x007fa6fc0da200>"

[17] pry(main)> User.where(name: "").name
=> "User"
```

**Comment by cschneid** [comment]
I believe this is only happening when we name queries in our Database addon. That code calls `layer.name.model` to name the object being operated on (where the `name` attribute should be a `ScoutApm::Utils::ActiveRecordMetricName` created by the `log` instrument we install). If that model attr is a AR_Relation object, it gets that full object instance name instead of the actual model class we expect.

I'm not yet sure how the AR_Relation object gets into our ActiveRecordMetricName class though. I've not been able to reproduce in a real Rails app yet. Some quick inspection of the `log` code in master rails seems to indicate that it expects a literal string of SQL, not any sort of Arel object.

**Comment by itsderek23** [comment]
@cschneid - note that #204 tweaks how queries are named. I added you as a reviewer.

**Comment by dlanderson** [comment]
Haven't see n this in a long while. Possible #204 did the job. Closing
