### ISSUE TITLE
Using `HEROKU_APP_NAME` as the default app name on Heroku

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_ruby#209]
Apps deployed to Heroku can enable a labs feature that makes dyno metadata available [docs](https://devcenter.heroku.com/articles/dyno-metadata). One of the env vars exposed is `HEROKU_APP_NAME`. 

If available, we should use this as the application name in Scout. It frequently contains the environment, allowing us to monitor the same app in different environments w/o any confusion on the user's part.

I imagine this would be added as a layer in [config.rb](https://github.com/scoutapp/scout_apm_ruby/blob/memory_tracking/lib/scout_apm/config.rb).

**Comment by cschneid** [comment]
One pattern I've seen used on heroku is an env var who's value is which env var to go look for.

`SCOUT_APP_NAME_ENV="HEROKU_APP_NAME"` basically.

That would be a nice general purpose config layer - and then we could automatically set it during heroku provisioning. At worse the agent looks for it and fails to find it at start, and continues in the exact same manner as it does now.
