### ISSUE TITLE
Sequel ORM Support

### ISSUE THREAD

**Issue by pabloh** [scoutapp/scout_apm_ruby#222]
Many of us use [Sequel](https://github.com/jeremyevans/sequel) with ruby instead of ActiveRecord, are there any plans to add integration for it eventually?

**Comment by gencer** [comment]
I doubt it. See #95

**Comment by harrikauhanen** [comment]
I think it's coming sooner or later: https://github.com/scoutapp/scout_apm_ruby/issues/95#issuecomment-461282578

Perhaps this duplicate issue can be closed (@cschneid)

**Comment by cschneid** [comment]
Closing as duplicate, thank you.

I will have an update in the other issue.
