### ISSUE TITLE
Ability to disable sending the remote ip in transaction traces

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#227]
We report the remote ip of the request (which is typically the IP of the user) when collecting a transaction trace ([see examples in code](https://github.com/scoutapp/scout_apm_ruby/search?utf8=%E2%9C%93&q=remote_ip&type=)). 

Security-conscience customers may wish to prevent recording this. Add an option to the agent to disable setting the remote ip.

Perhaps `collect_remote_ip` as an option, with a default of `true`.

**Comment by AndriiAkulov** [comment]
PR: https://github.com/scoutapp/scout_apm_ruby/pull/229

**Comment by dlanderson** [comment]
The `collect_remote_ip` option was added in 2.4.21
