### ISSUE TITLE
scout causes Interrupt exception to be ignored when loading config

### ISSUE THREAD

**Issue by notEthan** [scoutapp/scout_apm_ruby#230]
bit of a corner case, but hitting ctrl+c or otherwise raising an Interrupt exception (or SystemExit or some others) when an application that uses scout is booting up may result in incorrect behavior.

to reproduce: hit ctrl+c while scout is loading its config. obviously this may be easier said than done since it's generally a thing that should take microseconds. could probably put a `<% sleep 60 %>` or so in a scout config to level that playing field. I got randomly lucky/unlucky hitting ctrl+c at the right time to trigger this behavior.

expected behavior: the `Interrupt` interrupts scout in loading its config, and is handled by a configured interrupt handler, which will presumably cause the application to exit.

actual behavior: scout rescues the `Interrupt`, causing scout to potentially use the wrong config and the application to not receive the Interrupt. scout gives a message looking like:

```
$ RAILS_ENV=production rails s
=> Booting WEBrick
=> Rails 5.2.1 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
^C[Scout] [11/17/18 06:37:52 +0000 xx (17552)] INFO : Failed loading configuration file (/opt/xx/config/scout_apm.yml): exit. ScoutAPM will continue starting with configuration from ENV and defaults
[2018-11-17 06:37:52] INFO  WEBrick 1.3.1
[2018-11-17 06:37:52] INFO  ruby 2.3.8 (2018-10-18) [x86_64-linux-gnu]
[2018-11-17 06:37:52] INFO  WEBrick::HTTPServer#start: pid=17552 port=3000
```

suggested code changes:

first: don't rescue Exception in https://github.com/scoutapp/scout_apm_ruby/blob/v2.4.20/lib/scout_apm/config.rb#L404 - in fact, never rescue Exception. audit all your code and fix everything that looks like `rescue Exception`. it is wrong. the fix is a thing that I first stumbled upon in rspec: 
https://github.com/rspec/rspec-support/blob/v3.8.0/lib/rspec/support.rb#L132-L140
copy/paste that somewhere convenient (that little block of code is so useful somebody should probably put it in its own gem) and instead `rescue AllExceptionsExceptOnesWeMustNotRescue`. 

second (not strictly in scope of this issue, but it's on the next line so I'll mention it as well): better error message handling. in https://github.com/scoutapp/scout_apm_ruby/blob/v2.4.20/lib/scout_apm/config.rb#L405 you only show the exception message, which in the above example is just `exit`. not useful. if you're trying to debug an issue when your config is misbehaving, you want all the information - you should definitely be including the exception class there, and you should include the backtrace as well, since (I've just checked) erb does tell `eval` where the code comes from and so will include a meaningful entry in the exception backtrace pointing inside the config yml. so something like:

```ruby
rescue AllExceptionsExceptOnesWeMustNotRescue => e
  logger.info("Failed loading configuration file (#{@resolved_file_path}). ScoutAPM will continue starting with configuration from ENV and defaults. Exception was #{e.class}: #{e.message}#{e.backtrace.map { |bt| "\n  #{bt}" }.join('')}")
  @file_loaded = false
end
```

pinging @cschneid in particular as the blame says you are the relevant author.

**Comment by dlanderson** [comment]
Thanks! Closed by #436
