### ISSUE TITLE
DevTrace JS Error - payload.metadata is undefined

### ISSUE THREAD

**Issue by Nittarab** [scoutapp/scout_apm_ruby#235]
I get this errors:

![screenshot from 2018-12-01 16-45-36](https://user-images.githubusercontent.com/6181406/49330007-9d680f00-f588-11e8-942f-bcfe095989a8.png)

Env:
Rails 5.2.1
Ruby 2.5.3
Turbolinks 5.2

**Comment by cschneid** [comment]
Thank you for the report. I'm going to rename this and tag it as DevTrace.

**Comment by cschneid** [comment]
And so people can find this via google, the error in text form is: 

```
TypeError: payload.metadata is undefined
```

**Comment by Nittarab** [comment]
I think the problem could be relative to the route config:

```
get '*all', to: 'application#route_not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
```

Before use active storage was:
`match '*unmatched', to: 'application#route_not_found', via: :all`

**Comment by Nittarab** [comment]
@cschneid any news?
