### ISSUE TITLE
[detailed-traces] Duplicate `request_id` entry in identity and tags?

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#240]
It looks like the new `request_id` field is placed in 2 places in the payload:

* identity
* tags

```
"identity"=>
  {"request_id"=>"req-3e1432463fe08dbaa2ecec3ffd6a9424",
   "revision"=>"d76086b",
   "host"=>"dlite.local",
   "start_instant"=>"2018-12-14T13:36:42.927546-07:00",
   "stop_instant"=>"2018-12-14T13:36:43.240325-07:00",
   "type"=>"Web",
   "naming"=>{"path"=>"/apps/checkin.scout?key=7g5aWw9kN0cQ5i7ak4So&name=Scout+APM+%28Development%29", "code"=>""},
   "score"=>{"total"=>0, "percentile"=>0, "age"=>0, "memory_delta"=>0, "allocations"=>0}},
 "tags"=>{"allocations"=>240748, "mem_delta"=>0, "slow_jobs"=>2, "slow_transactions"=>2, "request_id"=>"req-3e1432463fe08dbaa2ecec3ffd6a9424", "user_ip"=>"::1"},
```

Any reason? For clarity, thinking we pick one.

**Comment by cschneid** [comment]
A side effect of adding it to a request's context hash. All context fields get added as tags. Use the one in identity, and we'll roll back the context one later. We need it for now since the old-style traces don't have anywhere else to put the id.

**Comment by itsderek23** [comment]
Got it. Thanks!

**Comment by itsderek23** [comment]
Note - this was changed to `transaction_id` in https://github.com/scoutapp/scout_apm_ruby/commit/02f4b654e0612f637a97a62858c3a460c501dea6
