### ISSUE TITLE
Handle too many spans more elegantly

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#248]
Currently, in `detailed-traces`, we shut off recording spans once 500 are recorded:

https://github.com/scoutapp/scout_apm_ruby/commit/67488e252522b2b30f843f1d059dc92622528315

We should handle this more elegantly. This current limit was established as a safeguard during the BETA. This likely involves some agent + UI decisions for aggregating these calls together.

**Comment by cschneid** [comment]
The limit here is about how we send spans in the payload after a transaction is finished. There's an existing limiting system that we should revisit that limits the collection of spans during a transaction. 

**Concerns in the payload**:

* Data size - we want to keep the network size of each payload down to a reasonable size.
* Parsing and processing time - if a trace has thousands and thousands of spans, it is harder to performantly ingest and process them.
* Needs of the UI - a trace view on the UI can't reasonably make use of thousands of spans of the same type. A user doesn't have much use to view the 454th copy of an n+1 SQL call and find any more info than any other randomly chosen call. But start & stop times of large groups of spans are important to the UI. This needs more definition and thinking on how we will display over-limit spans.

**Ideas I've had on the agent side**:

* "Merged Span" - if enough children spans are the same name, record a single record with many start/stop timestamp pairs. This works well for an n+1 situation, a repeated view partial, and similar.
* "Counted Span" - if there are enough spans we may run into size issues with the number of timestamps we can record. In that case, we can stop recording timestamps, and fall back to a counter. (1843 spans of type SQL/User#find). A start/stop time for the whole set would still be recorded.

**Comment by itsderek23** [comment]
Thanks @cschneid for laying this out so elegantly.

Right now, I'm thinking of diving into this after addressing more isolated UI bugs w/the trace. This touches a lot of pieces.

I'm thinking we revisit as we get closer to Ruby GA.

**Comment by itsderek23** [comment]
I think the most common case is many spans w/the same name (ex: 1843 spans of type SQL/User#find), probably not many uniquely named spans.

Strictly thinking from the UI-side, I wonder if makes sense to just do a "Counted Span" versus "Merged Span". This span would be tagged with something like `merged` and have a `call_count` or similar field.
