### ISSUE TITLE
Scout APM does not appear to consider http.rb time as HTTP

### ISSUE THREAD

**Issue by ibrahima** [scoutapp/scout_apm_ruby#258]
Hi! I use [HTTP.rb](https://github.com/httprb/http) as an HTTP client in some places because it's nicer than other clients in some ways, and it seems that Scout does not track time spent in that library as HTTP. Instead it appears to consider that time as spent in the view or the controller depending on where the method was that triggered an HTTP call. It'd be great to get this accounting fixed. I am using scout_apm (3.0.0.pre28).

Thanks!

**Comment by ioquatix** [comment]
I will instrument `HTTP.rb` similar to https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/instruments/net_http.rb

**Comment by ibrahima** [comment]
That would be awesome, thank you!

**Comment by jonekdahl** [comment]
We're switching to http.rb and it would be great to have Scout instrumentation in place. :+1:

**Comment by jrothrock** [comment]
Reopening as we aren't instrumenting HTTP.rb calls in the latest versions of Scout and HTTP.rb

**Comment by jrothrock** [comment]
Closing this issue in favor of the above
