### ISSUE TITLE
Possible to never collect traces from a High Throughput, Fast Endpoint

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#264]
## Short Explanation:

The situation:

• A relatively fast, high throughput endpoint
• Enough other endpoints that are slower

The first time each minute the fast endpoint happens - it is stored in the ScoredItemSet. This invokes `.call` which turns a intermediate trace thunk into a real stored one, and most importantly, resets the Age counter we keep.

Then sometime during the minute, other endpoints fill up and bump out the fast endpoint.

This happens every minute, which means that we both: Never hold the endpoint's trace through the whole minute, and also never start building up 'age' which would build up enough score to force a trace to get through at some point.

## More Explanation:

When a request finishes, it gets put into a thunk-style object that gets handed to the storage system. If it's sufficiently "interesting", it gets turned into a real trace object and stored. This is done to avoid doing a bunch of work for traces we know will get tossed almost immediately. But once stored, the trace isn't safe yet. If another more interesting trace comes in, it can get bumped out.

We use the [ScoredItemSet](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/scored_item_set.rb) to collect up the most interesting set of these traces.  It relies on a score, calculated on the Thunk by [SlowRequestPolicy](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/slow_request_policy.rb).  When a SlowRequest thunk is turned into a real trace, it calls `SlowRequestPolicy#stored!` which resets the `age` aspect of the policy for that endpoint.

## See-Also

We'll need to check our ingestion pipeline as well when we fix this because we use a similar algorithm to merge the checkins from many different servers into a single set of traces to store.

**Comment by dlanderson** [comment]
This should be able to be resolved by using a custom SlowRequestPolicy #364
