### ISSUE TITLE
Rails: Scout rewrites my custom asset host when monitoring requests

### ISSUE THREAD

**Issue by tolgap** [scoutapp/scout_apm_ruby#285]
I use a separate host for serving assets. For that, I use this line in `config/initializers/asset.rb`:

```ruby
Rails.application.config.action_controller.asset_host = ENV.fetch('ASSET_HOST')
```

This worked perfect, up until I add `gem 'scout_apm'` into my Gemfile to do some profiling. I think Scout wraps all responses somehow and rewrites asset URLs on its own.

I don't think this is expected behaviour.

**Comment by ioquatix** [comment]
Do you mind providing more details? What is it rewriting it to?

**Comment by tolgap** [comment]
If you set a specific asset host in your application init, it won't be used when `scout_apm` is required.

so if I have set an `ASSET_HOST` as `https://example.com`, instead of `http://localhost:3000`. Normally my assets will be served from `https://example.com`.

But when you include `scout_apm` in your Gemfile, the entire ASSET_HOST is ignored, and all assets are served with relative paths (thus being served from http://localhost:3000).
