### ISSUE TITLE
Noisy warning from Parser (AutoInstrument)

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#286]
Seen on APM itself. When the parser library loads to do AutoInstruments, it warns if the patch version of Ruby doesn't match what it expects.

There are dozens of warnings like this emitted during a deploy.

The warnings don't seem to cause problems, just noise. It'd be nice to quiet them.

```
      01 warning: parser/current is loading parser/ruby24, which recognizes
      01 warning: 2.4.7-compliant syntax, but you are running 2.4.5.
      01 warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

**Comment by ioquatix** [comment]
I wonder if we can do this upstream.

**Comment by jonekdahl** [comment]
The author of Parser has publicly stated that the warning is not going away. What you could do is offer instructions on how to make sure that you have a version of Parser that matches your Ruby version, which I believe involves upgrading either one or locking the versions to a known good combination (we're using `ruby '2.6.5'` and `gem 'parser', '~> 2.6.5.0'` in the Gemfile of our app).

**Comment by ioquatix** [comment]
@jonekdahl can you link us to this declaration?

**Comment by jonekdahl** [comment]
@ioquatix This is the comment I was thinking about: https://github.com/rubocop-hq/rubocop/issues/1819#issuecomment-95280926

**Comment by dlanderson** [comment]
The solution here is to make sure the `parser` gem is set to the correct version for the version of ruby that's running. Another option is to use a gem which can be configured to ignore the warnings, like [in this example](https://github.com/rubocop/rubocop/issues/1819#issuecomment-769278581):

```
# config/initializers/warning_ignores.rb

### https://github.com/jeremyevans/ruby-warning

Warning.ignore(/warning: parser/)
```
