### ISSUE TITLE
getting a syntax error on deploy

### ISSUE THREAD

**Issue by ioquatix** [scoutapp/scout_apm_ruby#287]
getting a syntax error on deploy

```
I, [2019-09-19T23:26:12.525601 #20423]  INFO -- : Refreshing Gem list
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.7-compliant syntax, but you are running 2.4.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/scout_apm-2.6.0/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `compile': members_controller.rb:32: syntax error, unexpected tOP_ASGN, expecting keyword_end (SyntaxError)
roy'"]){department.members} -= [::ScoutApm::AutoInstrument("
                              ^
        from /home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/scout_apm-2.6.0/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
        from /home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
```

_Originally posted by @mathieujobin in https://github.com/scoutapp/scout_apm_ruby/pull/247#issuecomment-533345475_

**Comment by ioquatix** [comment]
@mathieujobin can you please let me know if this fixes your issue?

**Comment by mathieujobin** [comment]
@ioquatix I could deploy to staging and production today.

looks like its happy, I have yet to discover the changes in the stats dashboard, this is exciting

**Comment by ioquatix** [comment]
Awesome! Let me know how you find the instrumentation.

**Comment by mathieujobin** [comment]
something seemed to be missing, ...

under timeline, I noticed some SQL was not showing the backtrace like before. it shown some highlevel `around_action` method, hiding where that query was being executed.

so I have disabled it

![image](https://user-images.githubusercontent.com/99191/66285960-27e87000-e90a-11e9-8191-1490bd7c217e.png)

the charts look very much different.

**Comment by mathieujobin** [comment]
the SQL query looks much more accurate though..

**Comment by ioquatix** [comment]
@dlanderson maybe you have some thoughts on this?

**Comment by mathieujobin** [comment]
I don't know if this is useful, but I am attaching another graph for a single endpoint

![image](https://user-images.githubusercontent.com/99191/66287442-ce377400-e910-11e9-9573-00a94c8e0ba7.png)

**Comment by mathieujobin** [comment]
sorry to keep posting here, I don't want to be annoying. I am not too sure under which issue you will want to fill this in. this is just out of interest that I share...

doesn't this graph clearly shows how the auto-instrument is missing something?

![image](https://user-images.githubusercontent.com/99191/66312105-f04de800-e94a-11e9-94e4-a0763986484f.png)

**Comment by dlanderson** [comment]
Hi @mathieujobin - looking at the chart it does seem you have higher response time without AutoInstruments. Let me investigate a bit more and I'll follow up

**Comment by dlanderson** [comment]
@mathieujobin Would you mind deploying AutoInstruments again for a few hours with debug logging turned on? Set `log_level: debug` in your `config/scout_apm.yml` file. If you don't mind, please ping support@scoutapm.com when you deploy so we can take a look.
