### ISSUE TITLE
Add instrumentation for Mongoid 7.x

### ISSUE THREAD

**Issue by jonekdahl** [scoutapp/scout_apm_ruby#293]
After upgrading to Mongoid 7 we no longer seem to have Scout instrumented Mongo DB calls. This is what the Scout log says about Mongoid on startup:

```
INFO : Instrumenting Mongoid 2.x
```

With Mongoid 6, the instrumentation was working and this is what the log said on startup:

```
INFO : Instrumenting Mongoid 2.x
INFO : Instrumenting Mongoid 5.x/6.x
```

Relevant versions

 * ruby: 2.6.3
 * scout_apm: 2.6.2
 * mongoid: 7.0.5
 * mongo: 2.10.2

**Comment by cschneid** [comment]
Hi @jonekdahl, I don't have time to fully confirm compatibility but I've created a branch that allows the Mongoid instrument to install on 7.x. I quickly checked instrumentation points we use, and they don't appear to have changed.

Can you give the `mongoid7` branch of this agent a try?

`gem 'scout_apm', git: 'https://github.com/scoutapp/scout_apm_ruby.git', branch: 'mongoid7'`

**Comment by jonekdahl** [comment]
Hi @cschneid, I have tried the mongoid7 branch on a new Rails 5 API app. I can confirm that it records some MongoDB time, but I haven't done any extensive testing.

I also tried it on a new Rails 6 API app, but for some reason I don't see any MongoDB time at all in Scout (just Router, Middleware and Controller). Perhaps that should be a different issue though.

**Comment by cschneid** [comment]
@jonekdahl is your Rails 6 app a new standalone app you could share? Maybe I can hunt down what's up quickly, otherwise it'll take a bit to dive into this.

**Comment by jonekdahl** [comment]
@cschneid I think the Rails 6 issue was a false alarm because it works with a bigger dataset. I guess there was so little MongoDB time that Scout just doesn't show it, could that be the case?

**Comment by cschneid** [comment]
We do hide any items that are faster than 1ms. Reduces clutter in the UI for parts of a request which can't be optimized. Sorry if that tripped you up!

I'll merge the mongoid7 branch and get a new release out next week. Thanks for helping!

**Comment by jonekdahl** [comment]
@cschneid How about that release? :wink:
