### ISSUE TITLE
I am not able to test my API's using scout_apm gem in ruby backend.

### ISSUE THREAD

**Issue by gbalodi** [scoutapp/scout_apm_ruby#294]
I am not able to test my API's using scout_nom gem in ruby backend.
Is there any way to test ruby API's via scout_npm?

**Comment by cschneid** [comment]
@gbalodi, I'm not sure I understand. This gem is the agent component of the hosted [Scout APM](https://scoutapm.com) service. We are a production monitoring tool, measuring things like Middleware, SQL, HTTP, Template and similar times inside Rails and other web frameworks.

Can you clarify what you're attempting?

**Comment by gbalodi** [comment]
@cschneid It seems I have misunderstood somethings on my end. I was actually looking for a gem that could provide me the same features as the **scout_apm_ruby** gem but for Rails API only project.

Please close this issue on your end. 

And, I would appreciate, if you could point me to the right direction where I could find the same features as you are offering in this gem but for Rails API project.

**Comment by cschneid** [comment]
Our Ruby agent does work fine with Rails API projects. We track Controller, SQL, Net::HTTP, and similar. If you use the view system, we will instrument that too (jbuilder and such).

[Give us a try](https://scoutapm.com/users/sign_up) with our two week trial, and email us at support@scoutapm.com if you run into any issues. It should "just work" for your use

**Comment by exocode** [comment]
> Our Ruby agent does work fine with Rails API projects. 

But `devtrace` won't work, it breaks the whole app.

**Comment by dlanderson** [comment]
Closing as requested by @gbalodi 
@exocode If you're running into an issue that does not currently have an issue filed, please do create a new one and we'll take a look.
