### ISSUE TITLE
Improve Ruby 1.8 compatibility

### ISSUE THREAD

**Issue by s01ipsist** [scoutapp/scout_apm_ruby#311]
The documentation specifies that the gem is compatible with Ruby 1.8.7 but bundler will fail to install because of a dependency issue.

The gem has a dependency on `parser`
https://github.com/scoutapp/scout_apm_ruby/blob/master/scout_apm.gemspec#L31

Parser requires Ruby 2.0 since version 2.5.0 a few years ago
https://github.com/whitequark/parser/commit/e15819c1063ac9a21a9d7d790faf0d6ffee1093c

This can be worked around by pinning to an earlier version of `parser`
https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v2402-2017-11-13
`gem 'parser', '2.4.0.2'`

or could be built into the gemspec with something like
```
if RUBY_VERSION < "2.0"
  s.add_runtime_dependency "parser", '< 2.5.0'
else
  s.add_runtime_dependency "parser"
end
```

It's amazing that you still support Ruby 1.8! Helpful for our legacy app until it gets current.

**Comment by cschneid** [comment]
Closing this since we've stopped supporting 1.8.7 (Sorry!). If you still use 1.8.7, the older versions of our agent still work and we can help you get setup. Contact us at support@scoutapm.com.
