### ISSUE TITLE
cannot find proc/cpuinfo file while running specs

### ISSUE THREAD

**Issue by pdxmeghan** [scoutapp/scout_apm_ruby#328]
In running specs locally, I get this error:
```
 Errno::ENOENT:
      No such file or directory @ rb_sysopen - /proc/cpuinfo
```

Has anybody run into this issue before? I can't find any information online about it.

**Comment by cschneid** [comment]
`/proc/cpuinfo` is a linux-only magic file that contains all the details about your computer's CPU.

Scout checks if the file exists, then reads it to determine processor count (see environment.rb). We do our best, but it's no big deal if it's wrong either.

What platform are you running these tests on? I am pretty sure the `File.exist?` check we have should prevent any errors, in test or actual usage.

**Comment by dlanderson** [comment]
No reply in over a year - please reopen with more information.
