### ISSUE TITLE
All partials rendered recorded as "Unknown partial" with rails 6.0

### ISSUE THREAD

**Issue by shadwell** [scoutapp/scout_apm_ruby#335]
Having upgraded an application to Rails 6 (6.0.2.2) I'm seeing "Unknown partial" for all partials rendered. Consequently they're all grouped together as a single entry in the time breakdown.

![image](https://user-images.githubusercontent.com/1128231/82995398-72367280-9ffb-11ea-86b8-57fdef3a3f6c.png)

Looks like it could be to do with how `render_partial` is monkey patched ( https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/instruments/action_view.rb#L81 ) . `@template` doesn't appear to be set the same way in rails 6 as with earlier versions so it's always nil.

To further complicate matters it appears that the actionview code that does the partial rendering has changed again since 6.0.2.2.

**Comment by cschneid** [comment]
I have also pushed a `rails6-master-partial-naming` branch with some initial work with what's on Rails master, but I'm going to wait for it to be properly released before wiring it up and merging.

**Comment by cschneid** [comment]
This should be released in scout_apm 2.6.8
