### ISSUE TITLE
NoMethodError: undefined method 'notify' for ScoutApm::ErrorService:Module

### ISSUE THREAD

**Issue by davidmccoy** [scoutapp/scout_apm_ruby#348]
Hello! Scout is encountering and error itself when trying to handle Sidekiq errors. The error occurs in one of the new Scout error reporting classes added here: 

https://github.com/scoutapp/scout_apm_ruby/pull/345

The error is `NoMethodError: undefined method 'notify' for ScoutApm::ErrorService:Module` and originates from `lib/scout_apm/error_service/sidekiq.rb:30`:

```
::Sidekiq.configure_server do |config|
  config.error_handlers << proc { |ex, context| ScoutApm::ErrorService.notify(ex, context.merge(:custom_controller => context["class"])) }
end
```

Here is the backtrace: `NoMethodError: undefined method 'notify' for ScoutApm::ErrorService:Module`

```
/bundler/gems/scout_apm_ruby-9799cb846f16/lib/scout_apm/error_service/sidekiq.rb:30 in block (2 levels) in <module:ScoutApm>
/gems/sidekiq-5.2.7/lib/sidekiq/exception_handler.rb:20 in block in handle_exception
/gems/sidekiq-5.2.7/lib/sidekiq/exception_handler.rb:18 in each
/gems/sidekiq-5.2.7/lib/sidekiq/exception_handler.rb:18 in handle_exception
/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:177 in rescue in process
/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:168 in process
/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83 in process_one
/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71 in run
/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16 in watchdog
/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25 in block in safe_thread
Caused by Sidekiq::JobRetry::Skip: Sidekiq::JobRetry::Skip
```

Unfortunately, I can't downgrade to a previous version of this gem because I need to be on this branch to resolve certificate errors: https://github.com/scoutapp/scout_apm_ruby/pull/345

**Comment by dlanderson** [comment]
Sorry @davidmccoy - I made the SSL branch against master and we have some unreleased code there. I've made a new branch based on our 2.6.8 release: [2_6_8-cert_file](https://github.com/scoutapp/scout_apm_ruby/tree/2_6_8-ssl_cert_file)

Please use that branch until I can get that out as a proper release. Thanks!

**Comment by davidmccoy** [comment]
Closing this as it was resolved. Thanks!
