### ISSUE TITLE
Support for Ruby 3.0.0

### ISSUE THREAD

**Issue by kapso** [scoutapp/scout_apm_ruby#367]
Requesting support for Ruby `3.0.0`

Thanks.

**Comment by StanBoyet** [comment]
@scoutapm-dev Is there any ETA for this? We ~are~ were in the process of updating our apps and it's a bit funny that the only thing preventing us from doing so is Scout's gem 😬 Especially since we've learned about some features in your (great btw!) [article](https://scoutapm.com/blog/ruby-3-features).

Thanks!

**Comment by dlanderson** [comment]
@StanBoyet Sorry about that - we tried to get to it before the holiday break. It's a priority this week.

**Comment by cschneid** [comment]
Can anybody is able try out the `ruby-3` branch and report back? Tests pass, and it looks ok on our test application, but there's more to do before a full release.

It appears that the kwargs changes over the course of the 2.x line of rubies are fairly incompatible, and we need to continue supporting rather old ruby versions. A full release will be forthcoming once I can be confident about our instrumentation on all the ruby versions.

```
gem 'scout_apm', git: 'https://github.com/scoutapp/scout_apm_ruby.git', branch: 'ruby-3'
```

**Comment by yuki24** [comment]
@cschneid I just tested it in a tiny hobby app and it seems to be working fine so far.

**Comment by zokioki** [comment]
@cschneid Have been running it on a small project as well for a few days - no issues yet.

**Comment by cschneid** [comment]
Thank you both for the feedback. I'll get a proper release out as soon as I can and update here.

**Comment by kapso** [comment]
@cschneid Any plans for a release soon? Thanks.

**Comment by cschneid** [comment]
I'm hoping to have a release out Tomorrow or Monday (the 18th) - I have a bit more validation testing against older Rubies to get to still.
