### ISSUE TITLE
Problem with Rails 2 and exceptions

### ISSUE THREAD

**Issue by eric** [scoutapp/scout_apm_ruby#37]
There is an extra argument in the [rails 2](https://github.com/scoutapp/scout_apm_ruby/blob/d3403206aaeaabca73ca6ce04b8bfa57a4483d33/lib/scout_apm/instruments/action_controller_rails_2.rb#L24) integration that causes an exception.

The method only takes 2 arguments.

**Comment by cschneid** [comment]
Thank you for your report. I'm not sure how that code lasted there - the behavior it was doing (reporting error count) is handled further along in the file, where we overwrite `perform_action`, in the call `req.error!`.

Sorry for any problems this caused you.

I've pushed a fix to master in a7b3370 and it will go out with the next release.  If you're needing the change sooner, point your gem reference to that commit.  Contact support@scoutapp.com if you need any help with that.
