### ISSUE TITLE
JavaScript Console Errors - "unique_id", "minimize.png", "logo.png"

### ISSUE THREAD

**Issue by jakesorce** [scoutapp/scout_apm_ruby#375]
1. Cannot read property 'unique_id'
2. minimize.png:1 GET http://localhost:3000/admin/addTrace/instant/minimize.png 404 (Not Found)
3. logo.png:1 GET http://localhost:3000/admin/addTrace/instant/logo.png 404 (Not Found)

See attached screenshots for more info. Causing a lot of error noise in our console for our devs. We are using Rails 6 with webpacker

<img width="543" alt="Screen Shot 2021-01-19 at 9 13 37 AM" src="https://user-images.githubusercontent.com/801470/105063302-d13c7200-5a38-11eb-949c-32bd1bb22f7f.png">
<img width="1678" alt="Screen Shot 2021-01-19 at 11 03 05 AM" src="https://user-images.githubusercontent.com/801470/105074682-eec40880-5a45-11eb-8a6f-e6194581869c.png">

**Comment by cschneid** [comment]
Thank you for the report - we'll be taking a look as soon as we can.

**Comment by jakesorce** [comment]
Looking forward to an update. Thank you!

**Comment by cschneid** [comment]
Hi, it looks like the `http://localhost:3000/admin` portion of the URLs in the screenshot are set via the config argument `SCOUT_DIRECT_HOST`. Are you overriding that? It's a debug and development configuration value, and should not be set normally.

It defaults to our own host (`https://apm.scoutapp.com`) where we provide the images and the script. 

If you're still seeing this, can you check your configuration, and if you don't see anything send an email to us at support@scoutapm.com and we'll help identify where that config is sneaking in.
