### ISSUE TITLE
Deprecation Warning with Rails 6.2 about connection_config

### ISSUE THREAD

**Issue by tisba** [scoutapp/scout_apm_ruby#388]
We are running on Rails 6.2 (Ruby 2.7.2) and see the following deprecation warnings:

```
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead) 
(called from raw_database_adapter at /usr/local/bundle/gems/scout_apm-2.6.8/lib/scout_apm/framework_integrations/rails_3_or_4.rb:74)
```

I don't understand why `framework_integrations/rails_3_or_4.rb` is involved in a Rails 6.2 app, but I also did not spend much time to dig into it. In case you need more information, let me know.

**Comment by j1wilmot** [comment]
This is being addressed in https://github.com/scoutapp/scout_apm_ruby/pull/365

**Comment by cschneid** [comment]
#365 is merged, and will be released early next week.
