### ISSUE TITLE
Truncate vs. Drop Large SQL Statements

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#40]
`SQLSanitizer#scrubbed` drops queries that exceed 1000 chars ([code](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/utils/sql_sanitizer.rb#L72)). These can frequently be slow queries (more complex queries are frequently more expensive). Rather than dropping these, how about:

> If length > 1000, append "..." to a 1000-length truncated string

The "..." should appear in our sanitized query so the UI makes it clear the query was truncated.

I think it is more involved than just str[0..999] on L78. We probably only want to do this if the string is encoded properly and isn't binary.

**Comment by jsturg** [comment]
Any update on this?

**Comment by itsderek23** [comment]
We could probably bump this up significantly - competitors have this at 16384. 

We may still want some sort of safeguard...concern would be recording a large+N+1 query.

**Comment by itsderek23** [comment]
Simple compromise: just bump up to 4,000 chars.
