### ISSUE TITLE
Fix Capistrano integration for deploy markers

### ISSUE THREAD

**Issue by andre** [scoutapp/scout_apm_ruby#43]
The capistrano deploy hook needs to use scout_apm's app name for the environment the app is being **deployed to**. 

The `DeploysController#create` identifies the app via the name provided. But, if you have a different app name specified for your local development environment, it will try to associate the deploy with the development app, not the production or staging app.

**Comment by andre** [comment]
```
W, [2016-07-08T15:25:29.227405 #31819]  WARN -- : /deploy_hook FAILED: {"errors":{"app":["can't be blank"]}}
W, [2016-07-08T15:25:29.227545 #31819]  WARN -- : Error on checkin to https://apm.scoutapp.com/apps/deploy.scout?key=KEY&name=Scout+APM+%28Development%29
```

**Comment by cschneid** [comment]
The error handling should be nicer too - maybe with a hint on "ohh, we
couldn't get your name, that's a shame. How 'bout you use this special
syntax we baked up for ya!"
