### ISSUE TITLE
ActionDispatch::RemoteIp::IpSpoofAttackError

### ISSUE THREAD

**Issue by dobrite** [scoutapp/scout_apm_ruby#44]
Looks like the gem raises when attempting to access `remote_ip`: ` from gems/scout_apm-1.5.0/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:64:in `process_action'`

```ruby
req = ScoutApm::RequestManager.lookup
path = ScoutApm::Agent.instance.config.value("uri_reporting") == 'path' ? request.path : request.fullpath
req.annotate_request(:uri => path)
req.context.add_user(:ip => request.remote_ip) # :boom:
req.set_headers(request.headers)
req.web!
```

I removed the IPs in the error message, but I think the important bit is that they don't match.

In my own app, with another gem, I rescued with the empty string. Perhaps that, or some identifier (e.g. `SPOOFED_IP`) or some such would make sense?

```
gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:125:in `calculate_ip': IP spoofing attack?! HTTP_CLIENT_IP="<redacted>" HTTP_X_FORWARDED_FOR="<redacted>" (ActionDispatch::RemoteIp::IpSpoofAttackError)
    from gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:144:in `to_s'
    from gems/actionpack-4.2.5.2/lib/action_dispatch/http/request.rb:231:in `remote_ip'
    from gems/scout_apm-1.5.0/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:64:in `process_action'
    from gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:137:in `process'
    ... tons of rails middleware stack traces removed
```

**Comment by cschneid** [comment]
Sorry about that, and thanks for the report!

I'll catch that error in the next version we release.  I didn't realize that what looked like an accessor `.remote_ip` would raise an exception.

**Comment by dobrite** [comment]
Fantastic. Thanks for the really quick turnaround! 👍

**Comment by cschneid** [comment]
This should be fixed in the newest release of the agent. `1.5.4`. Let me know if you have any other issues, either here, or at `support@scoutapp.com`
