### ISSUE TITLE
SystemStackError vendor/ruby-3.0.3/lib/ruby/3.0.0/set.rb:344 stack level too deep after adding new relic

### ISSUE THREAD

**Issue by dorianmariefr** [scoutapp/scout_apm_ruby#443]
After adding New Relic I get:

<img width="986" alt="Screenshot 2022-01-10 at 18 56 12" src="https://user-images.githubusercontent.com/58794487/148814998-0fb6e9a8-35f3-475b-97a6-cf9ad530b79e.png">

**Comment by dlanderson** [comment]
Hi @dorianmariefr - apologies for the conflicting gem interaction. Can you try listing 'scout_apm' before newrelic in the gemfile and see if that works for you?  This is due to different approached in instrumenting libraries between Scout and New Relic gems.

**Comment by dorianmariefr** [comment]
thanks, I received the same advice from the support, should fix it, seems like it's documented
