### ISSUE TITLE
Initialize error when upgrading to Sidekiq Pro

### ISSUE THREAD

**Issue by kanejamison** [scoutapp/scout_apm_ruby#444]
We're upgrading to Sidekiq Pro and getting exceptions from `/lib/scout_apm/background_job_integrations/sidekiq.rb`.

Currently on Rails 6.0.0 rc1, hosted on Heroku, and using Scout via the Heroku add-on with config vars set up, so we don't have a Scout initializer or config file. We're using current 'scout_apm' gem, not tied to a specific version.

We get the following exception when our Heroku workers try to start:

![image](https://user-images.githubusercontent.com/918780/149851882-4c50361f-889b-4957-9db7-7575d22d8939.png)

![image](https://user-images.githubusercontent.com/918780/149851811-5f50ac45-767b-47c9-a3da-9654521e5e37.png)

Workers can't start at all, so it freezes our worker queue.

I can't find any documentation about using Scout with Sidekiq Pro, so I'm wondering if this is a known error, or some type of config setting we're missing? Or would Sidekiq Pro be considered a library that requires custom instrumentation?

We are now using custom gem path instead of the standard sidekiq gem, in case that is a reference that affects the initialize process:

```
source "https://gems.contribsys.com/" do
  gem 'sidekiq-pro'
end
```

**Comment by mjobin-mdsol** [comment]
rails 6.0 rc1 ? scout_apm 2.5.2 ? 

I think you should at least be using scout 4.x

**Comment by kanejamison** [comment]
> rails 6.0 rc1 ? scout_apm 2.5.2 ? 
> 
> 
> 
> I think you should at least be using scout 4.x

Our gemfile is `gem 'scout_apm'` - I was assuming we were getting recent versions so I'm unsure why 2_5_2 is in the stack trace.

Ruby version is 2.6.3.

**Comment by kanejamison** [comment]
It was an upgrade issue - `bundle update scout_apm` resolved it.

Newb problem - thank you for your help!

**Comment by dlanderson** [comment]
Glad you found it!
