### ISSUE TITLE
Parser gem required in Gemfile

### ISSUE THREAD

**Issue by plindsayaltrio** [scoutapp/scout_apm_ruby#445]
I was wondering why auto instruments wasn't working and it was because of the changes made in this PR.
https://github.com/scoutapp/scout_apm_ruby/pull/440

This PR checks whether `Parser::TreeRewriter` is defined and bails out early if it isn't.

The problem is for applications that do not explicitly include `parser` in there Gemfile it will not yet be defined and will never reach the [codepath where Scout requires it](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/auto_instrument/parser.rb#L2)

The workaround is to explicitly add `parser` to the application Gemfile. Recommend updating docs to include this or reverting/changing the above PR.

**Comment by vladkosarev** [comment]
We have the same issue.
