### ISSUE TITLE
Exception in Rails app throws another exception in Scout

### ISSUE THREAD

**Issue by kellym** [scoutapp/scout_apm_ruby#45]
```
wrong number of arguments (3 for 2)
    .../scout_apm-1.4.6/lib/scout_apm/instruments/action_controller_rails_2.rb:24:in `track!'
```

This is in Ruby 1.8.7.

**Comment by kellym** [comment]
I commented out the exception handling in our bundle temporarily, but we're having to disable Scout because of this issue -- it breaks our custom error page and also masks all our legitimate bugs with this one.

**Comment by itsderek23** [comment]
@kellym,

Sorry for the issues - try `bundle update scout_apm`. This was addressed in [1.5.0](https://github.com/scoutapp/scout_apm_ruby/issues/37).

**Comment by kellym** [comment]
Awesome, thanks -- sorry for not checking for an update, I thought we were already at newest. :+1:

**Comment by itsderek23** [comment]
NP Kelly - let us know if you have any issues (support@scoutapp.com).
