### ISSUE TITLE
Issue installing Scout APM Ruby in development

### ISSUE THREAD

**Issue by krishnadiamesso** [scoutapp/scout_apm_ruby#479]
```
To use DevTrace, our free, no-signup, in-browser development profiler:

Add the gem to your Gemfile:
# Gemfile
gem 'scout_apm'
Start your Rails app with the SCOUT_DEV_TRACE environment variable:
SCOUT_DEV_TRACE=true rails server
```
After starting the server with SCOUT_DEV_TRACE=true rails server, where am I supposed to go to see the profiler?

**Comment by brennacodes** [comment]
@krishnadiamesso - I had the same question. After you get your server going, navigate to whatever page you're wanting to benchmark and there should be a small rectangle at the bottom lefthand corner of the screen with the time it took to load. When you click that, you can open up more info on where that measurement came from. 
<img width="269" alt="Screenshot 2023-08-22 at 8 17 40 AM" src="https://github.com/scoutapp/scout_apm_ruby/assets/98294995/91e6587a-b7fa-4d86-b61f-8667802d740b">

**Comment by krishnadiamesso** [comment]
> @krishnadiamesso - I had the same question. After you get your server going, navigate to whatever page you're wanting to benchmark and there should be a small rectangle at the bottom lefthand corner of the screen with the time it took to load. When you click that, you can open up more info on where that measurement came from. <img alt="Screenshot 2023-08-22 at 8 17 40 AM" width="269" src="https://user-images.githubusercontent.com/98294995/262381807-91e6587a-b7fa-4d86-b61f-8667802d740b.png">

@brennacodes 
Hello Brenna, Thank you so much for this. I will try it out. you have better eyes than I do. 👍
