### ISSUE TITLE
[BUG] SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by doutatsu** [scoutapp/scout_apm_ruby#485]
<img width="638" alt="image" src="https://github.com/scoutapp/scout_apm_ruby/assets/4270980/3d7d2818-22af-425a-b79a-e37f9f22c8cb">

This issue first came up in August and I had to disable Scout completely to fix this. I was hoping it would get addressed by this point, but the bug is still there and is basically app breaking bug - my background jobs fail due to Scout error

**Comment by lancetarn** [comment]
Hello @doutatsu 
Sorry for the trouble here. This can happen when Scout and another gem patch the same target in different ways. There are two workarounds that we are familiar with.

One is to [load the Scout gem first](https://scoutapm.com/docs/ruby/troubleshooting#stackleveltoodeep-error)
Another is to [change the instrumentation to prepend](https://scoutapm.com/docs/ruby/configuration#library-instrumentation-method)

If neither of these help, please reach out to support @ scoutapm.com and we will try to sort it out!

**Comment by doutatsu** [comment]
Thank you for the help - the first seems to have worked, and I'll keep the second point in mind as well if things deteriorate again
