### ISSUE TITLE
add license to gemspec

### ISSUE THREAD

**Issue by wireframe** [scoutapp/scout_apm_ruby#52]

**Comment by cschneid** [comment]
Our license file is located at: https://github.com/scoutapp/scout_apm_ruby/blob/master/LICENSE.md

It is unfortunately not open source. I've [added](https://github.com/scoutapp/scout_apm_ruby/commit/630d19e3f120ece44be75e86914d8e255be8b005) the license field as `Proprietary (See LICENSE.md)`.
