### ISSUE TITLE
Grape compatibility?

### ISSUE THREAD

**Issue by adeviadoug** [scoutapp/scout_apm_ruby#56]
I see you are beginning to support grape: https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/instruments/grape.rb

Question, what versions of Grape do you support? We're running 0.13.0 and saw this error when we tried to upgrade to v2.0 of the scout_apm_ruby gem:

Message	ArgumentError: wrong number of arguments (1 for 0)
Backtrace 
grape.rb  32  run_with_scout_instruments(...)
[GEM_ROOT]/gems/scout_apm-2.0.0/lib/scout_apm/instruments/grape.rb:32:in `run_with_scout_instruments'

**Comment by cschneid** [comment]
Sorry for the issue! For the time-being, you can disable the Grape instrument by adding a section to your scout_apm.yml file like:

```
production:
  disabled_instruments:
    - Grape
```

I'll be taking a look at your version of Grape, and we'll contact you directly.

**Comment by cbillen** [comment]
We experienced the same issue, please let us know when fixed

**Comment by jakeNiemiec** [comment]
+1

**Comment by cschneid** [comment]
I just pushed a change ( SHA fd0abf8f7 ) to a new `older-grapes` branch.

@adeviadoug 
@cbillen 
@jakeNiemiec
 
Could one or all of you try this in staging?  I'm pretty confident in it, but we don't have a particularly complex Grape setup to test again.

Update your gemfile with:

```ruby
gem 'scout_apm', git: 'https://github.com/scoutapp/scout_apm_ruby.git', branch: 'older-grapes'
```

Then I'll merge it in and get it released fully.

**Comment by mrloop** [comment]
Ran into issue, tried older-grapes branch and fixes issue for me.

**Comment by adeviadoug** [comment]
@cschneid in testing the `older-grapes` on another server we're seeing instrumentation in Scout and no errors being logged. 👍

**Comment by cschneid** [comment]
I just merged `older-grapes` branch in. It'll go out with our next normal release (2.1.6).

I'm closing this issue, contact us at support@scoutapp.com with any questions that may come up.
