### ISSUE TITLE
Looking for a way to avoid `start`ing

### ISSUE THREAD

**Issue by matthewrudy** [scoutapp/scout_apm_ruby#90]
My app has 18 deployments (6x "dev", 6x "staging", 6x "production").

We're just testing Scout on one of these ("dev-sg").

However, we get debug messages on every deployment.

```
$ heroku run rails c --app other_server
Running rails c on ⬢ other_server... up, run.3306 (Hobby)
[Scout] [02/19/17 01:23:07 +0000 run.3306 (4)] INFO : Attempting to start Scout Agent [2.1.22] on [run.3306]
[Scout] [02/19/17 01:23:07 +0000 run.3306 (4)] WARN : Monitoring isn't enabled for the [production] environment. Not starting agent
Loading production environment (Rails 5.0.1)
[1] pry(main)> ScoutApm::Agent.instance.apm_enabled?
=> false
[2] pry(main)> ScoutApm::Agent.instance.started?
=> false
[3] pry(main)> ScoutApm::Agent.instance.background_worker_running?
=> nil
```

This happens because no matter whether `apm_enabled?` is true or not
the Railtie tries to run `ScoutApm::Agent.instance.start`, which always emits these messages

https://github.com/scoutapp/scout_apm_ruby/blob/c6592a0/lib/scout_apm.rb#L156

Is there a nice way to avoid these warnings from being emitted?
From what I can see it's unavoidable right now.

**Comment by itsderek23** [comment]
Hi @matthewrudy,

One suggestion: change the `log_level` to `error` in your `config/scout_apm.yml` file. This should prevent the info and warn-level messages in the sample above. Example:

```yaml
common: &defaults
  log_level: error
```

**Comment by matthewrudy** [comment]
@itsderek23 that's a great suggestion, let me try!

**Comment by itsderek23** [comment]
@matthewrudy,

I'm going to close this for now, but if you have issues, please comment and we'll investigate further.

**Comment by matthewrudy** [comment]
@itsderek23 thanks.
