### ISSUE TITLE
Rails API only mode automatic support

### ISSUE THREAD

**Issue by Tybot204** [scoutapp/scout_apm_ruby#99]
Currently Scout includes instruments on `ActionController::Base`, and having your app controllers inherit from anything else (like `ActionController::Metal` or `ActionController::API`) requires manually including instruments. Rails 5 when run in API only mode has a config option set inside `application.rb`: `config.api_only = true`. It would be awesome to check this configuration at runtime and include instruments in `ActionController::API` as well!

**Comment by itsderek23** [comment]
@cschneid - is this addressed by #102?

**Comment by cschneid** [comment]
@Tybot204 as Derek says, this is handled by #102, and was shipped in agent version 2.1.26.
